version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    restart: always
    container_name: vaultwarden
    env_file:
      - ./vaultwarden.env
    volumes:
      - vaultwarden_data:/data
    expose:
      - "80"
      - "3012"

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 443:443
    env_file:
      - vaultwarden.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  backup:
    image: ttionya/vaultwarden-backup:latest
    container_name: vaultwarden-backup
    restart: always
    env_file:
      - ./vaultwarden.env
    volumes:
      - vaultwarden_data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
     
volumes:
  vaultwarden_data:
  caddy_data:
  caddy_config:
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
